name: Build and Deploy Website

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BUCKET: www.jerometaruc.com
      DIST: dist
      REGION: us-west-1
      DIST_ID: E1QCAXL5U14ZB4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build static website
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Deploy to S3
        run: aws s3 sync ${{ env.DIST }} s3://${{ env.BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
